---
- name: activate subscription on RHEL
  redhat_subscription:
    state:  present
    username: "{{ RH_SUBSCRIPTION_USERNAME }}"
    password: "{{ RH_SUBSCRIPTION_PASSWORD }}"
    autosubscribe: true

